pull_request_rules:
  - name: Automatically merge Greenkeeper PRs on CI success
    conditions:
      - status-success=Test
      - status-success=ci/codesandbox
      - status-success=greenkeeper/verify
      - author=greenkeeper[bot]
    actions:
      merge:
        method: merge
  - name: Automatically merge Greg's PRs on CI success
    conditions:
      - status-success=Test
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=codeclimate
      - author=GregBrimble
    actions:
      merge:
        method: merge
