name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
        with:
          fetch-depth: 1
      - name: Install
        uses: actions/npm@1.0.0
        with:
          fetch-depth: 1
          args: install
      - name: Lint
        uses: actions/npm@1.0.0
        with:
          fetch-depth: 1
          args: run lint
      - name: Test
        uses: actions/npm@1.0.0
        with:
          fetch-depth: 1
          args: run test:coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
